openapi: 3.0.2
info:
  title: Paynet RESTFul Spring Boot Project
  description: Paynet Interview Task
  termsOfService: terms
  contact:
    name: Asad Ganiev
    url: https://twitter.com/asadganiev
    email: asadganiev@gmail.com
  version: "1.0"
servers:
  - url: http://localhost:9000
    description: Spring Boot Local Server
paths:
  /v1/users/signup:
    post:
      tags:
        - Users
      summary: New User
      description: Register New User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          description: User Created
          headers:
            Location:
              description: Location of the created customer
              style: simple
              explode: false
              schema:
                type: string
                format: uri
                example: http://example.com/v1/users/{assignedIdValue}
        400:
          description: Bad Request
        409:
          description: User with such username already exists
  /v1/user/login:
    post:
      tags:
        - Users
      summary: login
      description: PaynetUser login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          description: PaynetUser Created
          headers:
            Location:
              description: Location of the created customer
              style: simple
              explode: false
              schema:
                type: string
                format: uri
                example: http://example.com/v1/users/{assignedIdValue}
        400:
          description: Bad Request
        409:
          description: Conflict
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        username:
          maxLength: 50
          minLength: 2
          type: string
          example: johndoe
        password:
          maxLength: 50
          minLength: 8
          type: string
          example: "******"
        firstName:
          maxLength: 50
          minLength: 2
          type: string
          example: John
        lastName:
          maxLength: 50
          minLength: 2
          type: string
          example: Doe
        street:
          type: string
          maxLength: 100
          minLength: 2
          example: Alisher Navai 33a
        region:
          type: string
          maxLength: 100
          minLength: 2
          example: Samarkand
        city:
          type: string
          maxLength: 100
          minLength: 2
          example: Samarkand
        zipCode:
          type: integer
          example: 33701
      description: PaynetUser Object
  securitySchemes:
    JwtAuthToken:
      type: http
      scheme: bearer
      bearerFormat: JWT